### ISSUE TITLE
How to see sampled images?

### ISSUE THREAD

**Issue by TingTingin** [CarperAI/DRLX#15]
How to see the sampled images that are being used for the reinforcement while training?

**Comment by shahbuland** [comment]
Do you want to be able to see all the sampled images each epoch? Currently it only shows one batch. What would the desirable behavior be here; logging them to wandb?

**Comment by shahbuland** [comment]
They aren't saved... what would be the motivation behind wanting them saved if you don't mind my asking? Should be an easy enough feature to add though.

**Comment by tmabraham** [comment]
@TingTingin the Weights and Biases tracking shows this and logs image generations after every epoch.

**Comment by shahbuland** [comment]
Solved in #20
